hello

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,12 +39,11 @@ jobs:
         run: ls node_modules/@dylibso/xtp-bindgen || echo "Module not found"
 
       - name: "Debug: List type definitions"
-        run: ls node_modules/@dylibso/xtp-bindgen/*.d.ts || echo "Type definitions not found"
+        run: ls node_modules/@dylibso/xtp-bindgen/**/*.d.ts || echo "Type definitions not found"
 
       - name: Build
         run: |
           npm run build
-
 
       - name: Run test script
         run: |
