asdlk;jasd;lkajsd

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,7 +39,7 @@ jobs:
         run: ls node_modules/@dylibso/xtp-bindgen || echo "Module not found"
 
       - name: "Debug: List type definitions"
-        run: ls node_modules/@dylibso/xtp-bindgen/**/*.d.ts || echo "Type definitions not found"
+        run: ls node_modules/@dylibso/xtp-bindgen/dist/*.d.ts || echo "Type definitions not found"
 
       - name: Build
         run: |
